// https://github.com/MatteoGabriele/agentscan-action/blob/main/src/known-bots.ts
export const knownBots = new Set([
  'agentscanapp',
  'copilot',
  'dependabot',
  'dependabot-preview',
  'renovate',
  'renovate-bot',
  'greenkeeper',
  'github-actions',
  'stale',
  'snyk-bot',
  'codecov',
  'codecov-commenter',
  'coveralls',
  'travis-ci',
  'circleci',
  'appveyor',
  'azure-pipelines',
  'netlify',
  'vercel',
  'heroku',
  'aws-amplify',
  'eslintbot',
])
